spring.application.name=GymFlow

spring.datasource.url=jdbc:postgresql://localhost:5433/gymflow
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update

spring.main.web-application-type=none